apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - configmap.yaml
  - secret.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - user-service-deployment.yaml
  - user-service-service.yaml
  - api-gateway-deployment.yaml
  - api-gateway-service.yaml
  - hpa.yaml
  - network-policies.yaml
  - pdb.yaml

commonLabels:
  app.kubernetes.io/managed-by: kustomize
  app.kubernetes.io/part-of: devops-challenge
